# -*- coding: utf-8 -*-
"""Iris Flower Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DLXiDuMS2Hg_Kf8DQJ7Kto9pIeVtwRGt
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

dataset = load_iris()

print(dataset.DESCR)

x = dataset.data

y = dataset.target

y

x

plt.plot(x[:, 0][y == 0]* x[:, 1][y == 0], x[:, 1][y == 0]*x[:, 2][y == 0],'.r',label='Setosa')
plt.plot(x[:, 0][y == 1]* x[:, 1][y == 1], x[:, 1][y == 1]*x[:, 2][y == 1],'.g',label='Versicolour')
plt.plot(x[:, 0][y == 2]* x[:, 1][y == 2], x[:, 1][y == 2]*x[:, 2][y == 2],'.b',label='Virginica')
plt.legend()
plt.show()

from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y)

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()

log_reg.fit(x_train, y_train)

log_reg.score(x_test, y_test)

log_reg.score(x, y)